### ISSUE TITLE
Make sure changing a metadata does not turn it into a parameter

### ISSUE THREAD

**Issue by waliens** [jm-begon/clustertools#11]
I often have to pass the number of available processors (n_jobs) to the computations so that I can launch some code in parallel. 
If I launch a first batch of computation with one value of n_jobs, then change it for the next batch, clustertools starts considering n_jobs as a parameter of the grid.

**Comment by waliens** [comment]
Up @jm-begon
The idea would be to make available to the run method such parameters without considering it as parameter/metadata.

**Comment by jm-begon** [comment]
Commit eebaf331aa493ba111839738e6f23d2a67ceda69 add a new example (`011_environment_parameters.py`) which illustrates how to address this issue
