### ISSUE TITLE
Error message with datacube.diagnose() when maximum time reached

### ISSUE THREAD

**Issue by vahuynh** [jm-begon/clustertools#34]
When jobs can not complete because the maximum time is reached, I get the following error message when using the datacube.diagnose() function:

>  Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/ulg/sysmod/vananh/anaconda3/lib/python3.6/site-packages/clustertools/datacube.py", line 545, in diagnose
>     "Missing ratio": self._missing_ratio(ood),
>   File "/home/ulg/sysmod/vananh/anaconda3/lib/python3.6/site-packages/clustertools/datacube.py", line 522, in _missing_ratio
>     return float(len(ood))/self.size()
> ZeroDivisionError: float division by zero

**Comment by jm-begon** [comment]
Commit 350a2f2 (from branch dev) is stable and solves the ambigus error message. It will be merged in the master branch soon.

**Comment by jm-begon** [comment]
Commit 350a2f2f048ece7024031b9cfffbe55eeb4319e2 was integrated to master with merge #35
