### ISSUE TITLE
Add a way to discard some parameters combinations 

### ISSUE THREAD

**Issue by waliens** [jm-begon/clustertools#7]
Sometimes, some combinations of parameters are invalid. For instance, we can have floats parameters A and B and A that cannot be greater than B. The basic cartesian product will create invalid combinations with A greater than B. 

clustertools could provide some way of filtering the combinations using predicate functions for instance.

**Comment by jm-begon** [comment]
Solved in 36da01944dfc1afa9a511b551f89500502668774 (check `ConstrainedParameterSet`)
